/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.digikala_bootleg;

import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class ProductProfile extends javax.swing.JPanel {

    /**
     * Creates new form ProductProfile
     */
     private String productName;
    private String productDescription;
    private String productImageURL;
    private ProductModel productModel;
    private int userID;
    private int productID;
    private int productPrice;
    private int productQuantity;
    private int enteredProductQuantity;
    public ProductProfile(int productID,int productQuantity,String productName,String productDescription,int productPrice,int UID,ProductModel productModel/*,String productImageURL*/) throws Exception {
        initComponents();
         this.productName = productName;
        this.userID = UID;
        this.productModel = productModel;
        this.productDescription = productDescription;
        this.productPrice = productPrice;
        //this.productImageURL = productImageURL;
        this.productID = productID;
        this.productQuantity = productQuantity;
        productNameLabel.setText(this.productName);
        productDescriptionLabel.setText(this.productDescription);
        quantityLabel.setText(Integer.toString(productQuantity));
        String priceText = (productQuantity == 0)? "OUT OF STOCK" : Integer.toString(productPrice);  
        priceLabel.setText(priceText);
        quantitySpinner1.setValue(productModel.getShoppingCartProductQuantityByID(userID,productID));
        //image url
        
    }
    public String getProductName(){
        return productName;
    }
    public String getProductDescription(){
        return productDescription;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNameLabel = new javax.swing.JLabel();
        productIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productDescriptionLabel = new javax.swing.JTextPane();
        updateButton = new javax.swing.JButton();
        quantitySpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        quantityLabelText = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        priceLabelText = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        productNameLabel.setFont(new java.awt.Font("Source Code Pro Medium", 0, 14)); // NOI18N
        productNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        productNameLabel.setText("Product Name");

        productDescriptionLabel.setEditable(false);
        productDescriptionLabel.setBackground(new java.awt.Color(204, 204, 204));
        productDescriptionLabel.setBorder(null);
        productDescriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        productDescriptionLabel.setText("product descriptionproduct descriptionproduct descriptionproduct descriptionproduct descriptionproduct descriptionproduct descriptionproduct descriptionproduct descriptionproduct description");
        jScrollPane1.setViewportView(productDescriptionLabel);

        updateButton.setBackground(new java.awt.Color(51, 255, 51));
        updateButton.setForeground(new java.awt.Color(0, 0, 0));
        updateButton.setText("UPDATE");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Code Pro Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("In shopping cart:");

        quantityLabel.setFont(new java.awt.Font("Source Code Pro Medium", 0, 14)); // NOI18N
        quantityLabel.setForeground(new java.awt.Color(0, 0, 0));
        quantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantityLabel.setText("0");

        quantityLabelText.setFont(new java.awt.Font("Source Code Pro Medium", 0, 12)); // NOI18N
        quantityLabelText.setForeground(new java.awt.Color(0, 0, 0));
        quantityLabelText.setText("Quantity:");

        priceLabel.setFont(new java.awt.Font("Source Code Pro Medium", 0, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(0, 0, 0));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("0");

        priceLabelText.setFont(new java.awt.Font("Source Code Pro Medium", 0, 12)); // NOI18N
        priceLabelText.setForeground(new java.awt.Color(0, 0, 0));
        priceLabelText.setText("Price:");

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("COMMENTS");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(productIcon)
                                .addGap(319, 319, 319))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quantityLabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(priceLabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantitySpinner1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityLabelText)
                            .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabelText)
                            .addComponent(priceLabel))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(productIcon)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quantitySpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        this.enteredProductQuantity = (int)quantitySpinner1.getValue();
        enteredProductQuantity = Math.min(enteredProductQuantity, productQuantity);
        enteredProductQuantity = Math.max(enteredProductQuantity, 0);
        if (enteredProductQuantity == 0) return;
        ProductModel.setShoppingCartProductQuantity(userID, productID, enteredProductQuantity);
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CommentsPage(userID, productID).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabelText;
    private javax.swing.JTextPane productDescriptionLabel;
    private javax.swing.JLabel productIcon;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityLabelText;
    private javax.swing.JSpinner quantitySpinner1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
