/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.digikala_bootleg;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asus
 */
public class ShoppingCartProductProfile extends javax.swing.JPanel {
    private String productName;
    public String getProductName(){
        return productName;
    }
    private ProductModel productModel;
    private int userID;
    private int productID;
    private float productPrice;
    private int productQuantity;
    private float finalPrice;

    /**
     * Creates new form ShoppingCartProductProfile
     */
    public ShoppingCartProductProfile(int productID,int UID,ProductModel productModel) throws Exception {
        initComponents();
        this.productID = productID;
        this.productModel = productModel;
        this.productName = (String)productModel.getProductPropertyByID("name", productID);
        this.userID = UID;
        this.productQuantity = productModel.getShoppingCartProductQuantityByID(userID,productID);
        this.productPrice = (float)productModel.getProductPropertyByID("price", productID);
        this.finalPrice = productQuantity * productPrice;
        productNameJLabel.setText(productName);
        priceJLabel.setText(Float.toString(finalPrice));
        quantityJLabel.setText(Integer.toString(productQuantity));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNameJLabel = new javax.swing.JLabel();
        priceJLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        quantityJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        productNameJLabel.setFont(new java.awt.Font("Source Code Pro Medium", 0, 14)); // NOI18N
        productNameJLabel.setForeground(new java.awt.Color(0, 0, 0));
        productNameJLabel.setText("Product name");

        priceJLabel.setFont(new java.awt.Font("Source Code Pro Medium", 0, 14)); // NOI18N
        priceJLabel.setForeground(new java.awt.Color(0, 0, 0));
        priceJLabel.setText("26000");

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setText("REMOVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        quantityJLabel.setFont(new java.awt.Font("Source Code Pro Medium", 0, 14)); // NOI18N
        quantityJLabel.setForeground(new java.awt.Color(0, 0, 0));
        quantityJLabel.setText("34");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("X");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(quantityJLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(priceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(priceJLabel)
                    .addComponent(jButton1)
                    .addComponent(quantityJLabel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        productModel.removeProductFromShoppingCart(userID, productID);
        try {
            productModel.getShoppingCartProductProfiles();
        } catch (IOException ex) {
            Logger.getLogger(ShoppingCartProductProfile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ShoppingCartProductProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel priceJLabel;
    private javax.swing.JLabel productNameJLabel;
    private javax.swing.JLabel quantityJLabel;
    // End of variables declaration//GEN-END:variables
}
